version: 0.2

env:
  variables:
    # WARNING! you _must_ set this in the codebuild GUI.
    BUCKET_PREFIX: ""
    # this is set to the latest available planet if you don't override it in the GUI!
    PLANET_DATE: ""

phases:
  install:
    commands:
      - pip install pipenv
      - pipenv install --system --deploy
  build:
    commands:
      # set planet date to latest planet, if it wasn't already set by the environment.
      - >
          if [ -z "$PLANET_DATE" ]; then
            PLANET_DATE=`curl -Is https://planet.openstreetmap.org/planet/planet-latest.osm.bz2 |
                         grep "Location: " |
                         sed 's,.*/planet-\([0-9]\{6\}\).osm.bz2\r$,\1,;t ok;q 1;:ok'`;
          fi
      - python batch-setup/cron.py --bucket-prefix $BUCKET_PREFIX $PLANET_DATE
