logging: {config: /etc/tilequeue/logging.conf}
rawr:
  group-zoom: 10
  sources: [osm, wof, water_polygons, land_polygons, ne_10m_urban_areas]
  postgresql:
    host: ...
    port: 5432
    dbname: ...
    user: ...
    password: ...
  source:
    type: s3
    table-sources:
      planet_osm_line: &osm { name: osm, value: openstreetmap.org }
      planet_osm_point: *osm
      planet_osm_polygon: *osm
      planet_osm_ways: *osm
      planet_osm_rels: *osm
      wof_neighbourhood: { name: wof, value: whosonfirst.mapzen.com }
      water_polygons: &osmdata { name: shp, value: openstreetmapdata.com }
      land_polygons: *osmdata
      ne_10m_urban_areas: { name: ne, value: naturalearthdata.com }
  sink:
    type: s3
    s3:
      bucket: ...
      region: ...
      prefix: ...
      suffix: .zip
  label-placement-layers:
    point: ['earth', 'water']
    polygon: ['buildings', 'earth', 'landuse', 'water']
    linestring: ['earth', 'landuse', 'water']
  indexes:
    - type: osm
    - type: simple
      table: wof_neighbourhood
      layer: places
    - type: simple
      table: water_polygons
      layer: water
    - type: simple
      table: land_polygons
      layer: earth
    - type: simple
      table: ne_10m_urban_areas
      layer: landuse
      end_zoom: 10
  intersect: {type: none}
use-rawr-tiles: true
